//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.HR_Managment.Reports {
    
    
    public partial class EmployeeReports {
        
        /// <summary>
        /// ReportEmployeeByCountryShowHideHyperLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink ReportEmployeeByCountryShowHideHyperLink;
        
        /// <summary>
        /// ReportEmployeeByCountryPrintHyperLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink ReportEmployeeByCountryPrintHyperLink;
        
        /// <summary>
        /// ReportEmployeeByNationalitiesShowHideHyperLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink ReportEmployeeByNationalitiesShowHideHyperLink;
        
        /// <summary>
        /// ReportEmployeeByNationalitiesPrintHyperLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink ReportEmployeeByNationalitiesPrintHyperLink;
        
        /// <summary>
        /// pieChart1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.PieChart pieChart1;
    }
}
